export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const TAG_GROUPS_LOADED = 'TAG_GROUPS_LOADED';
export const REVIEWERS_LOADED = 'REVIEWERS_LOADED';
export const CUSTODIANS_LOADED = 'CUSTODIANS_LOADED';
